<a href="https://colab.research.google.com/github/zahira456/Zahira-Nur-Asyifa_2411532015_ML2526/blob/main/Praktikum3/TugasLogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
dataset_url = 'https://raw.githubusercontent.com/zahira456/Zahira-Nur-Asyifa_2411532015_ML2526/refs/heads/main/Praktikum2/Breast_cancer_data.csv'
df = pd.read_csv(dataset_url)
df.head()

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0
1,20.57,17.77,132.90,1326.0,0.08474,0
2,19.69,21.25,130.00,1203.0,0.10960,0
3,11.42,20.38,77.58,386.1,0.14250,0
4,20.29,14.34,135.10,1297.0,0.10030,0


In [4]:
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

Model tanpa scalling

In [6]:
model_no_scaling = LogisticRegression(max_iter=10000)

model_no_scaling.fit(X_train, y_train)

y_pred_no_scaling = model_no_scaling.predict(X_test)

print("Accuracy tanpa scaling:",
      accuracy_score(y_test, y_pred_no_scaling))

Accuracy tanpa scaling: 0.9298245614035088


Scalling

In [7]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
model_scaling = LogisticRegression(max_iter=10000)

model_scaling.fit(X_train_scaled, y_train)

y_pred_scaling = model_scaling.predict(X_test_scaled)

print("Accuracy dengan scaling:",
      accuracy_score(y_test, y_pred_scaling))

Accuracy dengan scaling: 0.9385964912280702


In [10]:
y_prob = model_scaling.predict_proba(X_test_scaled)[:,1]

In [11]:
thresholds = [0.3, 0.5, 0.7]

for t in thresholds:

    y_pred_threshold = (y_prob >= t).astype(int)

    print("\nThreshold:", t)
    print("Accuracy:", accuracy_score(y_test, y_pred_threshold))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred_threshold))


Threshold: 0.3
Accuracy: 0.9473684210526315
Confusion Matrix:
[[37  6]
 [ 0 71]]

Threshold: 0.5
Accuracy: 0.9385964912280702
Confusion Matrix:
[[39  4]
 [ 3 68]]

Threshold: 0.7
Accuracy: 0.9298245614035088
Confusion Matrix:
[[42  1]
 [ 7 64]]
